### ISSUE TITLE
'BasicNetworkDriver<>' does not exist

### ISSUE THREAD

**Issue by bpoc** [Unity-Technologies/multiplayer#25] opened 2019-04-18 16:03 UTC
This line from the documentation
`using UdpCNetworkDriver = Unity.Networking.Transport.BasicNetworkDriver<Unity.Networking.Transport.IPv4UDPSocket>;
`
Is throwing this error 

> The type or namespace name 'BasicNetworkDriver<>' does not exist in the namespace 'Unity.Networking.Transport' (are you missing an assembly reference?

**Comment by psuong** [comment] 2019-04-18 17:29
Hey there, they renamed `BasicNetworkDriver<>` to `GenericNetworkDriver<>`. The upgrade guide is in their [changelog](https://github.com/Unity-Technologies/multiplayer/blob/master/CHANGELOG.md).

**Comment by SDRob** [comment] 2019-04-21 08:57
Is this because of the addition of the pipelines?  Will the tutorials be rewritten to include them?

Thanks!

**Comment by LokoGD** [comment] 2019-04-22 10:44
Tried the new Multiplayer version (2019-04-16, in Unity 2019.1) with the new "GenericNetworkDriver<>" and i got an error beucase it asks for a second parameter.

**Comment by amandachatman** [comment] 2019-04-26 19:26
> Tried the new Multiplayer version (2019-04-16, in Unity 2019.1) with the new "GenericNetworkDriver<>" and i got an error because it asks for a second parameter.

Is there a fix for this? Downloaded repo today, Unity 2019.1, still seeing this issue.

**Comment by gra-am** [comment] 2019-04-27 01:23
I feel like a man in a cave with a candle.

I changed that line to `using UdpCNetworkDriver = Unity.Networking.Transport.UdpNetworkDriver; `

Then it told me to use NetworkEndPoint instead of IPEndpoint, however now it's warning me 'NetworkEndPoint' does not contain a constructor that takes 2 arguments.

Where can I look at NetworkEndPoint or any of the code for Unity.Networking.Transport? For the life of me I cannot find it in this repo, and any Google search returns deprecated UNet documentation.

**Comment by gra-am** [comment] 2019-04-27 01:33
In the if statement around line ~20 I changed `new IPEndPoint(IPAddress.Any, 9000)` to `new NetworkEndPoint()` and it got rid of the error, however who knows if it will work as intended, how do I know what the default constructor does?

**Comment by gra-am** [comment] 2019-04-27 02:01
Another problem around line ~72: `m_Driver.Send(m_Connections[i], writer);` requires three parameters instead of two. So I changed it to `m_Driver.Send(new NetworkPipeline(), m_Connections[i], writer);`

I'm willing to bet the syntax is good enough to be compiled but the logic is incredibly flawed.

**Comment by gra-am** [comment] 2019-04-27 02:23
The example client code is also a hotbed of errors relating to the syntax change.

**Comment by kursadacar** [comment] 2019-04-30 00:05
> Another problem around line ~72: `m_Driver.Send(m_Connections[i], writer);` requires three parameters instead of two. So I changed it to `m_Driver.Send(new NetworkPipeline(), m_Connections[i], writer);`
> 
> I'm willing to bet the syntax is good enough to be compiled but the logic is incredibly flawed.

You should create a pipeline. To do that you should use something like this:

`new NetworkPipeline pipeline = m_Driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));`

`new NetworkPipeline unreliable = m_Driver.CreatePipeline(typeof(NullPipelineStage));`



> In the if statement around line ~20 I changed `new IPEndPoint(IPAddress.Any, 9000)` to `new NetworkEndPoint()` and it got rid of the error, however who knows if it will work as intended, how do I know what the default constructor does?

You should use NetworkEndpoint now. IPEndPoint is no longer supported. 
You can define a new NetworkEndpoint like this:

`var net_ep = NetworkEndPoint.AnyIpv4;`
`net_ep.Port = 9000;`

**Comment by mfitzer** [comment] 2019-05-31 21:38
I have made the necessary changes to the ClientBehaviour and ServerBehaviour classes as well as added comments explaining what is going on. The Unity project can be downloaded from my GitHub repo: [Real-time_Multiplayer_Test](https://github.com/mfitzer/Real-time_Multiplayer_Test)

**Comment by peteyhayman** [comment] 2019-06-03 08:15
Thanks for the advice on using a NetworkEndpoint instead of IPEndPoint

Creating a network pipeline did not work for me, instead I went with a null pipeline like in the [ping server example](https://github.com/Unity-Technologies/multiplayer/blob/b7c2798078ab2408caf232b8775aa6ff9ac71ccd/sampleproject/Assets/Samples/Ping/PingServerBehaviour.cs#L91)

`driver.Send(NetworkPipeline.Null, connection, pongData);`

**Comment by timj-unity** [comment] 2019-11-29 19:28
NetworkPipeline.Null will be (slightly) faster than creating a pipeline with the null stage. The BasicNetworkDriver -> UdpNetworkDriver change is what you need.

**Closed by timj-unity** 2019-11-29 19:28 UTC
